### ISSUE TITLE
Update pip package

### ISSUE THREAD

**Issue by jantonio471** [max-plutonium/django-compositepk#2]
Hi! 

I install this package from pip, but it does not work by the django version (>= 2.0) then I install the package using pip with the github resouce, finally it works.

I see that some changes in github is not in the package installed with pip.

https://pypi.org/project/django-compositepk/

Update this package to pip is the option?! 

Thanks.

**Comment by max-plutonium** [comment]
Hi!

Sorry for late answer!

I am not a maintainer of the original repo. I cloned this repo from https://bitbucket.org/smileychris/django-compositepk

You can contact it's maintainer by this address: smileychris (at) gmail.com.

Good luks!

**Comment by jantonio471** [comment]
Thanks for your help, I close this issue.
